[package]
name = "loutre_hublot"
version = "0.1.0"
authors = ["Edgar Onghena <dev@edgar.bzh>"]
edition = "2018"

[dependencies]
dotenv = "0.15"
lettre = { version = "0.10.0-beta.3", features = ["rustls-tls", "file-transport"] }
log = "0.4"
rocket = "0.4"
